on:
  workflow_dispatch:
    inputs:
      input1:
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
        required: true

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
