on:
  workflow_dispatch:
    inputs:
      input1:
        type: choice
        options:
          - info
          - warning
          - debug
        required: true
        default: "info"


jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
